### PR TITLE
Add Anope registration and authentication API

### PR DESCRIPTION
**Pull request by linuxdaemon**

### CODE REVIEW

**Review by A-UNDERSCORE-D — COMMENTED** [review]
This requires at least one other approval and testing on the devnet before I will approve it. Looks good otherwise.

**Comment by linuxdaemon** [comment]
> This requires at least one other approval and testing on the devnet before I will approve it. Looks good otherwise.

This has been tested by me, waiting on further testing from @prawnsalad

**Comment by prawnsalad** [comment]
@linuxdaemon any info on how i can test it?

**Review by A-UNDERSCORE-D — COMMENTED** [review]
This still looks fine to me, but needs an approval from someone who understands CPP better than I do.

**Review by ghost — APPROVED** [review]
LGTM

**Comment by A-UNDERSCORE-D** [comment]
Following some additional considerations. While the code seems good (pending another look-over from me), I'd like some unit tests in place to make sure that it continues to work as expected.

**Comment by linuxdaemon** [comment]
> Following some additional considerations. While the code seems good (pending another look-over from me), I'd like some unit tests in place to make sure that it continues to work as expected.

Unit testing an anope module like this would require a full anope instance, as well as a full ircd for it to link to and clients to connect to the network. I don't think this is feasible to implement at this time

**Comment by A-UNDERSCORE-D** [comment]
Well that's unfortunate. As @sadieltm has signed off on it it *should* be fine. Tests in the future would be nice though

**Comment by linuxdaemon** [comment]
> Well that's unfortunate. As @sadieltm has signed off on it it _should_ be fine. Tests in the future would be nice though

I do plan to investigate testing options in the future, but with how the system stands, it's infeasible at this time. Despite the lack of continuous testing, it has been fully tested as it stands right now, is that sufficient for your approval @A-UNDERSCORE-D ?

**Review by A-UNDERSCORE-D — APPROVED** [review]

**Pull request merged**
